
/*
 * Filename: sc_events_type.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Signalclass
 */

#ifndef _H_DEFINE_SC_EVENTS_TYPE
#define _H_DEFINE_SC_EVENTS_TYPE

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SC_EVENTS_INCLUDES */
    
#include "statemachine_type.h"

/* USER CODE END SC_EVENTS_INCLUDES */



/**********************************************************************
 *       Type Definition for SC_EVENTS signal    
 **********************************************************************/

/* USER CODE START SC_EVENTS_USERDEFINITIONS */
//    typedef enum {
//        EV_KEYLEFT,
//        EV_KEYRIGHT,
//        EV_KEYRIGHTLONGPRESS,
//        EV_1MIN,
//        EV_250MS,
//        NONE
//    } EVENT_t;

/* USER CODE END SC_EVENTS_USERDEFINITIONS */

typedef 
/* USER CODE START SC_EVENTS_SIGNALDATADEFINITION */
struct
{
//	#error "Provide your data structure"
    
    STATE_event_t m_event;
    
} 
/* USER CODE END SC_EVENTS_SIGNALDATADEFINITION */
SC_EVENTS_data_t;

/* USER CODE START InitSC_EVENTS */
//#error "Provide a sensible init value"
#define SC_EVENTS_INIT_DATA ((SC_EVENTS_data_t){NONE})
/* USER CODE END InitSC_EVENTS */





/* USER CODE START SC_EVENTS_USERFUNCTIONS */

/* USER CODE END SC_EVENTS_USERFUNCTIONS */


#endif