/*
 * Filename: sp_common.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: The common global signal pool, all signals will be stored here
 * endaddr: ADR_SP_COMMON_END
 * name: sp_common
 * shortname: common
 * startaddr: ADR_SP_COMMON_START
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sp_common.h"



/* USER CODE START SP_COMMON_INCLUDE */

/* USER CODE END SP_COMMON_INCLUDE */

#include "sc_buttons.h"
#include "sc_buttons_type.h"
#include "sc_events.h"
#include "sc_events_type.h"
#include "sc_clockdata.h"
#include "sc_clockdata_type.h"



/* signal configuration */
/*
 * description: A Signal for the input buttons
 * indriver: default
 * name: so_buttons
 * onDataError: 0
 * onDataUpdate: 0
 * outdriver: 0
 * resource: res_buttons_Lock
 * shortname: buttons
 * signalclass: sc_buttons
 * signalpool: sp_common
 */

 

static const SC_BUTTONS_cfg_t SO_BUTTONS_cfg = 
{
   /* indriver           */  SC_BUTTONS_driverIn,
   /* outdriver          */  0,

   /* onUpdate           */  0,
   /* onError            */  0,
   /* taskCount onUpdate */  0,
   /* task list onUpdate */  NULL,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  TRUE,
   /* resource           */  res_buttons_Lock,
   
}; /* configuration so_buttons */


/* signal data */

SC_BUTTONS_t SO_BUTTONS_signal= 
{
   /* init value    */  SC_BUTTONS_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_BUTTONS_cfg,
}; /* data so_buttons */

/* signal configuration */
/*
 * description: A Signal for events
 * indriver: 0
 * name: so_events
 * onDataError: 0
 * onDataUpdate: ev_events_onData
 * outdriver: 0
 * resource: res_events_Lock
 * shortname: events
 * signalclass: sc_events
 * signalpool: sp_common
 */


/* The following array contains the receiving tasks for onUpdate signal events */
const TaskTypeArray so_events_updTasks = { tsk_control };
 

static const SC_EVENTS_cfg_t SO_EVENTS_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  0,

   /* onUpdate           */  ev_events_onData,
   /* onError            */  0,
   /* taskCount onUpdate */  1,
   /* task list onUpdate */  &so_events_updTasks,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  TRUE,
   /* resource           */  res_events_Lock,
   
}; /* configuration so_events */


/* signal data */

SC_EVENTS_t SO_EVENTS_signal= 
{
   /* init value    */  SC_EVENTS_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_EVENTS_cfg,
}; /* data so_events */

/* signal configuration */
/*
 * description: A Signal for the clock data
 * indriver: 0
 * name: so_clockData
 * onDataError: 0
 * onDataUpdate: 0
 * outdriver: default
 * resource: res_clockdata_Lock
 * shortname: clockData
 * signalclass: sc_clockData
 * signalpool: sp_common
 */

 

static const SC_CLOCKDATA_cfg_t SO_CLOCKDATA_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  SC_CLOCKDATA_driverOut,

   /* onUpdate           */  0,
   /* onError            */  0,
   /* taskCount onUpdate */  0,
   /* task list onUpdate */  NULL,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  TRUE,
   /* resource           */  res_clockdata_Lock,
   
}; /* configuration so_clockdata */


/* signal data */

SC_CLOCKDATA_t SO_CLOCKDATA_signal= 
{
   /* init value    */  SC_CLOCKDATA_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_CLOCKDATA_cfg,
}; /* data so_clockdata */



/*
 * Increments the age of the signals in this pool 
 */
void RTE_timertick_sp_common_tick(uint32_t tick){
   RTE_SC_BUTTONS_incAge( &SO_BUTTONS_signal, tick); 
   RTE_SC_EVENTS_incAge( &SO_EVENTS_signal, tick); 
   RTE_SC_CLOCKDATA_incAge( &SO_CLOCKDATA_signal, tick); 
   
}

/*
 * Reset all signals in this pool
 */
void RTE_reset_sp_common(){
   RTE_SC_BUTTONS_init( &SO_BUTTONS_signal); 
   RTE_SC_EVENTS_init( &SO_EVENTS_signal); 
   RTE_SC_CLOCKDATA_init( &SO_CLOCKDATA_signal); 
   
}		


