/*
 * Filename: swc_output.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Software component
 * name: swc_output
 * shortname: output
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_output.h"



/* USER CODE START SWC_OUTPUT_INCLUDE */

/* USER CODE END SWC_OUTPUT_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_OUTPUT_USERDEFINITIONS */

/* USER CODE END SWC_OUTPUT_USERDEFINITIONS */



/*
 * component: swc_output
 * cycletime: 250
 * description: Runnable
 * events: 
 * name: OUTPUT_updateDataOnTFT_run
 * shortname: updateDataOnTFT
 * signalIN: so_clockData
 * signalOUT: 
 * task: tsk_display
 */
void OUTPUT_updateDataOnTFT_run(RTE_event ev){
	
	/* USER CODE START OUTPUT_updateDataOnTFT_run */
    
    
    
    RTE_SC_CLOCKDATA_pushPort(&SO_CLOCKDATA_signal);
    
    SC_CLOCKDATA_data_t output = SC_CLOCKDATA_INIT_DATA;
    RTE_SC_CLOCKDATA_getThreadSafe(&SO_CLOCKDATA_signal, &output);
    
    output.m_hours.m_updateRequired = FALSE;
    output.m_minutes.m_updateRequired = FALSE;
    RTE_SC_CLOCKDATA_set(&SO_CLOCKDATA_signal, output);

    /* USER CODE END OUTPUT_updateDataOnTFT_run */
}

/*
 * component: swc_output
 * cycletime: 1000
 * description: Runnable
 * events: 
 * name: OUTPUT_blink1s_run
 * shortname: blink1s
 * signalIN: so_clockData
 * signalOUT: 
 * task: tsk_display
 */
void OUTPUT_blink1s_run(RTE_event ev){
	
	/* USER CODE START OUTPUT_blink1s_run */
    
    static boolean_t firstUse = TRUE;
    
    if (firstUse == TRUE){
        SC_CLOCKDATA_data_t output = SC_CLOCKDATA_INIT_DATA;
        RTE_SC_CLOCKDATA_getThreadSafe(&SO_CLOCKDATA_signal, &output);
        
        output.m_hours.m_updateRequired = TRUE;
        output.m_minutes.m_updateRequired = TRUE;
        RTE_SC_CLOCKDATA_set(&SO_CLOCKDATA_signal, output);
        
        
        firstUse = FALSE;
    }
    
//    RTE_SC_CLOCKDATA_pushPort(&SO_CLOCKDATA_signal);
 
    SC_CLOCKDATA_data_t output = SC_CLOCKDATA_INIT_DATA;
    RTE_SC_CLOCKDATA_getThreadSafe(&SO_CLOCKDATA_signal, &output);
    
    if (output.m_hours.m_editing == FALSE && output.m_minutes.m_editing == FALSE){
        output.blink = ~output.blink;
    
    } else {
        output.blink = TRUE;
    
    }
    
    
    
    
    RTE_SC_CLOCKDATA_set(&SO_CLOCKDATA_signal, output);
    RTE_SC_CLOCKDATA_pushPort(&SO_CLOCKDATA_signal);
    

    /* USER CODE END OUTPUT_blink1s_run */
}

/* USER CODE START SWC_OUTPUT_FUNCTIONS */

/* USER CODE END SWC_OUTPUT_FUNCTIONS */

