/*
 * Filename: swc_control.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Software component
 * name: swc_control
 * shortname: control
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_control.h"



/* USER CODE START SWC_CONTROL_INCLUDE */

/* USER CODE END SWC_CONTROL_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_CONTROL_USERDEFINITIONS */

/* USER CODE END SWC_CONTROL_USERDEFINITIONS */



/*
 * component: swc_control
 * cycletime: 0
 * description: Runnable
 * events: ev_events_onData
 * name: CONTROL_runStateMachine_run
 * shortname: runStateMachine
 * signalIN: so_events
 * signalOUT: so_clockData
 * task: tsk_control
 */
void CONTROL_runStateMachine_run(RTE_event ev){
	
	/* USER CODE START CONTROL_runStateMachine_run */

    /* USER CODE END CONTROL_runStateMachine_run */
}

/* USER CODE START SWC_CONTROL_FUNCTIONS */

/* USER CODE END SWC_CONTROL_FUNCTIONS */

