/*
 * Filename: swc_output.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Software component
 * name: swc_output
 * shortname: output
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_output.h"



/* USER CODE START SWC_OUTPUT_INCLUDE */

/* USER CODE END SWC_OUTPUT_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_OUTPUT_USERDEFINITIONS */

/* USER CODE END SWC_OUTPUT_USERDEFINITIONS */



/*
 * component: swc_output
 * cycletime: 250
 * description: Runnable
 * events: 
 * name: OUTPUT_updateDataOnTFT_run
 * shortname: updateDataOnTFT
 * signalIN: so_clockData
 * signalOUT: 
 * task: tsk_display
 */
void OUTPUT_updateDataOnTFT_run(RTE_event ev){
	
	/* USER CODE START OUTPUT_updateDataOnTFT_run */

    /* USER CODE END OUTPUT_updateDataOnTFT_run */
}

/*
 * component: swc_output
 * cycletime: 1000
 * description: Runnable
 * events: 
 * name: OUTPUT_blink1s_run
 * shortname: blink1s
 * signalIN: so_clockData
 * signalOUT: 
 * task: tsk_display
 */
void OUTPUT_blink1s_run(RTE_event ev){
	
	/* USER CODE START OUTPUT_blink1s_run */

    /* USER CODE END OUTPUT_blink1s_run */
}

/* USER CODE START SWC_OUTPUT_FUNCTIONS */

/* USER CODE END SWC_OUTPUT_FUNCTIONS */

