
/*
 * Filename: tsk_input.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Task doing work
 */

#ifndef _H_DEFINE_TSK_INPUT
#define _H_DEFINE_TSK_INPUT

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START TSK_INPUT_INCLUDES */

/* USER CODE END TSK_INPUT_INCLUDES */



/*
 * description: Task doing work
 * events: ev_250ms|ev_ButtonsPressed
 * mode: Cyclic and Event
 * name: tsk_input
 * shortname: input
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: ev_250ms
 * timertickperiod: 250
 */
DeclareTask(tsk_input);

/* USER CODE START TSK_INPUT_TASKUSERFUNCTION */

/* USER CODE END TSK_INPUT_TASKUSERFUNCTION */


#endif