/*
 * Filename: tsk_display.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Task doing work
 * events: ev_250ms
 * mode: Cyclic
 * name: tsk_display
 * shortname: display
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: ev_250ms
 * timertickperiod: 250
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "tsk_display.h"



/* USER CODE START TSK_DISPLAY_INCLUDE */

/* USER CODE END TSK_DISPLAY_INCLUDE */

#include "swc_output.h"



/* USER CODE START TSK_DISPLAY_USERDEFINITIONS */

/* USER CODE END TSK_DISPLAY_USERDEFINITIONS */

/*******************************************************************************
 * Runnable Tables from Activation Engine
 *******************************************************************************/

/* Cyclic Table */

const RTE_cyclicTable_t RTE_cyclicActivationTable_tsk_display[] = {
	{ OUTPUT_updateDataOnTFT_run, 250 },	//Runnable
	{ OUTPUT_blink1s_run, 1000 },	//Runnable
};
const uint16_t RTE_cyclicActivation_tsk_display_size = sizeof (RTE_cyclicActivationTable_tsk_display) / sizeof(RTE_cyclicTable_t); 


/*******************************************************************************
 * Task Body
 *******************************************************************************/


/*
 * description: Task doing work
 * events: ev_250ms
 * mode: Cyclic
 * name: tsk_display
 * shortname: display
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: ev_250ms
 * timertickperiod: 250
 */
TASK(tsk_display)
{
	/* ticktime of the task */
	static uint32_t ticktime = 0;

	/* USER CODE START TSK_DISPLAY_TASKBOBY_PRE */

	/* USER CODE END TSK_DISPLAY_TASKBODY_PRE */
    
    //Process all cyclic runnables which are due
    RTE_ProcessCyclicTable(RTE_cyclicActivationTable_tsk_display, RTE_cyclicActivation_tsk_display_size, ticktime);
	
	/* USER CODE START TSK_DISPLAY_TASKBODY_POST */

	/* USER CODE END TSK_DISPLAY_TASKBODY_POST */

	ticktime += 250;
	if (ticktime > 0xFFFFFF00) ticktime = 0;
	
	TerminateTask();
    
}


/*******************************************************************************
 * Interrupt Service Routines
 *******************************************************************************/

/* USER CODE START TSK_DISPLAY_ISR */

/* USER CODE END TSK_DISPLAY_ISR */

