
/*
 * Filename: tsk_display.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Task doing work
 */

#ifndef _H_DEFINE_TSK_DISPLAY
#define _H_DEFINE_TSK_DISPLAY

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START TSK_DISPLAY_INCLUDES */

/* USER CODE END TSK_DISPLAY_INCLUDES */



/*
 * description: Task doing work
 * events: ev_250ms
 * mode: Cyclic
 * name: tsk_display
 * shortname: display
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: ev_250ms
 * timertickperiod: 250
 */
DeclareTask(tsk_display);

/* USER CODE START TSK_DISPLAY_TASKUSERFUNCTION */

/* USER CODE END TSK_DISPLAY_TASKUSERFUNCTION */


#endif